# Generated by Django 6.1 on 2026-08-31 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='Enroll.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField(default=3)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='Enroll.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='Enroll.faculty'),
        ),
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_courses', to='Enroll.course')),
                ('responsible_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_offered_courses', to='Enroll.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField()),
                ('max_seats', models.IntegerField(default=30)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('offered_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Enroll.offeredcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, unique=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Enroll.curriculum')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ENROLLED', 'ลงทะเบียนสำเร็จ'), ('DROPPED', 'ถอนรายวิชา')], default='ENROLLED', max_length=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Enroll.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Enroll.student')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='Enroll.university'),
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_class', models.CharField(choices=[('CORE', 'วิชาแกน'), ('SPECIFIC', 'วิชาเฉพาะ'), ('GENERAL', 'วิชาทั่วไป')], max_length=10)),
                ('general_category', models.CharField(blank=True, choices=[('1', 'หมวด 1'), ('2', 'หมวด 2'), ('3', 'หมวด 3')], max_length=1, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='Enroll.course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='Enroll.curriculum')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('curriculum', 'course'), name='unique_curriculum_course')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_class', models.CharField(choices=[('CORE', 'วิชาแกน'), ('SPECIFIC', 'วิชาเฉพาะ'), ('GENERAL', 'วิชาทั่วไป')], max_length=10)),
                ('general_category', models.CharField(blank=True, choices=[('1', 'หมวด 1'), ('2', 'หมวด 2'), ('3', 'หมวด 3')], max_length=1, null=True)),
                ('min_credits', models.IntegerField(default=0)),
                ('max_credits', models.IntegerField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='Enroll.curriculum')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('curriculum', 'course_class', 'general_category'), name='unique_curriculum_requirement')],
            },
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('offered_course', 'section_number'), name='unique_offered_course_section'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'section'), name='unique_student_section_enrollment'),
        ),
    ]
